// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqCbqZkxjOCrDnmB6NZN4U3xMJpu5WScI',
    appId: '1:18045745008:web:d726a37e640e6fc80741b5',
    messagingSenderId: '18045745008',
    projectId: 'alzcare-740c1',
    authDomain: 'alzcare-740c1.firebaseapp.com',
    storageBucket: 'alzcare-740c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ6_I_jb2q-SFo3znkm3ZPxM9gsGlmbts',
    appId: '1:18045745008:android:fa9e9538144a86540741b5',
    messagingSenderId: '18045745008',
    projectId: 'alzcare-740c1',
    storageBucket: 'alzcare-740c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqiqmLDTvstwdoKIKHtGy8nkRgMxCsdP4',
    appId: '1:18045745008:ios:cb0a45f6c371fa8e0741b5',
    messagingSenderId: '18045745008',
    projectId: 'alzcare-740c1',
    storageBucket: 'alzcare-740c1.appspot.com',
    iosClientId: '18045745008-ods40hh0hqjjc67k7sq2nj5c619dc26i.apps.googleusercontent.com',
    iosBundleId: 'com.example.alzcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqiqmLDTvstwdoKIKHtGy8nkRgMxCsdP4',
    appId: '1:18045745008:ios:cb0a45f6c371fa8e0741b5',
    messagingSenderId: '18045745008',
    projectId: 'alzcare-740c1',
    storageBucket: 'alzcare-740c1.appspot.com',
    iosClientId: '18045745008-ods40hh0hqjjc67k7sq2nj5c619dc26i.apps.googleusercontent.com',
    iosBundleId: 'com.example.alzcare',
  );
}
